### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [sergioramos/remark-hint#19]
Hi!

remark is switching to a new parser internally ([micromark](https://github.com/micromark/micromark), [`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536)).
It seems this plugin should be fine, however, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by sergioramos** [comment]
thank you for the tip, appreciated @wooorm

**Comment by sergioramos** [comment]
Updated remark to v13 and tests are passing so I assume it is working with no change :)

https://github.com/sergioramos/remark-hint/commit/280c41ee9c17a622f2b58480c3017a69c5685b78

Thank you, again 👍
